# Generated by Django 4.1.6 on 2023-02-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_author_book_is_bestdelling_alter_book_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_bestdelling',
            new_name='is_bestselling',
        ),
    ]
